site_name: The Internals of Apache Kafka
site_url: https://books.japila.pl/kafka-internals
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of Apache Kafka

repo_name: kafka-internals
repo_url: https://github.com/japila-books/kafka-internals
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2022 Jacek Laskowski

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages
  - macros

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  book:
    title: Apache Kafka
    kafka_streams: https://books.japila.pl/kafka-streams-internals
  java:
    api: https://docs.oracle.com/en/java/javase/11/docs/api/java.base
  kafka:
    version: 3.2.1
    github: https://github.com/apache/kafka/tree/3.2.1
  scala:
    short_version: 2.13
    api: https://www.scala-lang.org/api/2.13.6
    docs: https://docs.scala-lang.org/
    spec: https://www.scala-lang.org/files/archive/spec/2.13
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
    - icon: fontawesome/brands/medium
      link: https://jaceklaskowski.medium.com

nav:
  - Home: index.md
  - Internals:
    - Overview: overview.md
    - AbstractConfig: AbstractConfig.md
    - AutoTopicCreationManager: AutoTopicCreationManager.md
    - BrokerMetadataCheckpoint: BrokerMetadataCheckpoint.md
    - Configurable: Configurable.md
    - DefaultAutoTopicCreationManager: DefaultAutoTopicCreationManager.md
    - FetchResponseData: FetchResponseData.md
    - InterBrokerSendThread: InterBrokerSendThread.md
    - Kafka: Kafka.md
    - KafkaApis: KafkaApis.md
    - KafkaConfig: KafkaConfig.md
    - Log: Log.md
    - LogManager:
      - log/index.md
      - LogCleaner:
        - log/LogCleaner.md
        - log/LogCleanerManager.md
        - log/CleanerConfig.md
        - log/CleanerThread.md
      - LogConfig: log/LogConfig.md
      - LogManager: log/LogManager.md
      - UnifiedLog: log/UnifiedLog.md
    - LogSegment: LogSegment.md
    - Partition: Partition.md
    - PartitionData: PartitionData.md
    - RequestHandlerHelper: RequestHandlerHelper.md
    - ReplicaAlterLogDirsThread: ReplicaAlterLogDirsThread.md
    - ReplicaManager: ReplicaManager.md
    - Server: Server.md
    - TopicConfig: TopicConfig.md
    - Utils: Utils.md
    - ZkAdminManager: ZkAdminManager.md
    - Zookeeper:
      - zk/AdminZkClient.md
      - zk/KafkaZkClient.md
  - Controller Broker:
    - controller/index.md
    - AbstractControllerBrokerRequestBatch: controller/AbstractControllerBrokerRequestBatch.md
    - ControllerBrokerRequestBatch: controller/ControllerBrokerRequestBatch.md
    - ControllerChannelManager: controller/ControllerChannelManager.md
    - ControllerContext: controller/ControllerContext.md
    - ControllerEvents:
      - ControllerEvent: controller/ControllerEvent.md
      - AutoPreferredReplicaLeaderElection: controller/AutoPreferredReplicaLeaderElection.md
      - TopicUncleanLeaderElectionEnable: controller/TopicUncleanLeaderElectionEnable.md
    - controller/ControllerEventManager.md
    - ControllerEventProcessor: controller/ControllerEventProcessor.md
    - controller/ControllerState.md
    - controller/ControllerEventThread.md
    - controller/KafkaController.md
    - PartitionStateMachine: controller/PartitionStateMachine.md
    - QueuedEvent: controller/QueuedEvent.md
    - ReplicaStateMachine: controller/ReplicaStateMachine.md
    - TopicDeletionManager: controller/TopicDeletionManager.md
    - ZkPartitionStateMachine: controller/ZkPartitionStateMachine.md
    - ZkReplicaStateMachine: controller/ZkReplicaStateMachine.md
  - Features:
    - Consumer Groups:
      - consumer-groups/index.md
      - consumer-groups/GroupCoordinator.md
      - consumer-groups/GroupMetadataManager.md
      - consumer-groups/OffsetConfig.md
    - Controller Election: controller/controller-election.md
    - Dynamic Broker Configuration:
      - dynamic-broker-configuration/index.md
      - dynamic-broker-configuration/BrokerConfigHandler.md
      - dynamic-broker-configuration/BrokerReconfigurable.md
      - dynamic-broker-configuration/ConfigHandler.md
      - dynamic-broker-configuration/DynamicBrokerConfig.md
      - dynamic-broker-configuration/DynamicThreadPool.md
      - TopicConfigHandler: dynamic-broker-configuration/TopicConfigHandler.md
      - ZkConfigManager: dynamic-broker-configuration/ZkConfigManager.md
    - Log Cleanup:
      - log-cleanup/index.md
    - Security:
      - Authentication: authentication.md
      - Authorization:
        - authorization/index.md
        - AclApis: authorization/AclApis.md
        - AclAuthorizer: authorization/AclAuthorizer.md
        - AuthHelper: authorization/AuthHelper.md
        - Authorizer: authorization/Authorizer.md
    - Transactions:
      - transactions/index.md
      - TransactionConfig: transactions/TransactionConfig.md
      - TransactionCoordinator: transactions/TransactionCoordinator.md
      - TransactionMarkerChannelManager: transactions/TransactionMarkerChannelManager.md
      - TransactionStateManager: transactions/TransactionStateManager.md
  - Broker:
    - broker/index.md
    - KafkaBroker: broker/KafkaBroker.md
    - KafkaServer: broker/KafkaServer.md
  - Clients:
    - clients/index.md
    - Admin:
      - clients/admin/index.md
      - AdminClientRunnable: clients/admin/AdminClientRunnable.md
    - Consumers:
      - clients/consumer/index.md
      - AbstractCoordinator: clients/consumer/AbstractCoordinator.md
      - AbstractPartitionAssignor: clients/consumer/AbstractPartitionAssignor.md
      - Consumer: clients/consumer/Consumer.md
      - ConsumerConfig: clients/consumer/ConsumerConfig.md
      - ConsumerCoordinator: clients/consumer/ConsumerCoordinator.md
      - ConsumerMetadata: clients/consumer/ConsumerMetadata.md
      - ConsumerNetworkClient: clients/consumer/ConsumerNetworkClient.md
      - ConsumerPartitionAssignor: clients/consumer/ConsumerPartitionAssignor.md
      - Fetcher: clients/consumer/Fetcher.md
      - KafkaConsumer: clients/consumer/KafkaConsumer.md
      - Preferred Read Replica: clients/consumer/preferred-read-replica.md
      - SubscriptionState: clients/consumer/SubscriptionState.md
      - TopicPartitionState: clients/consumer/TopicPartitionState.md
    - CommonClientConfigs: clients/CommonClientConfigs.md
    - KafkaClient: clients/KafkaClient.md
    - Metadata: clients/Metadata.md
    - MetadataUpdater: clients/MetadataUpdater.md
    - NetworkClient: clients/NetworkClient.md
    - NetworkClientUtils: clients/NetworkClientUtils.md
    - Producers:
      - clients/producer/index.md
      - BufferPool: clients/producer/BufferPool.md
      - Callback: clients/producer/Callback.md
      - DefaultPartitioner: clients/producer/DefaultPartitioner.md
      - KafkaProducer: clients/producer/KafkaProducer.md
      - Partitioner: clients/producer/Partitioner.md
      - Producer: clients/producer/Producer.md
      - ProducerBatch: clients/producer/ProducerBatch.md
      - ProducerConfig: clients/producer/ProducerConfig.md
      - ProducerInterceptors: clients/producer/ProducerInterceptors.md
      - RecordAccumulator: clients/producer/RecordAccumulator.md
      - Sender: clients/producer/Sender.md
      - TransactionManager: clients/producer/TransactionManager.md
    - Serde: Serde.md
    - Serdes: Serdes.md
  - Tools:
    - tools/index.md
    - kafka-acls:
      - tools/kafka-acls/index.md
      - AclCommand: tools/kafka-acls/AclCommand.md
      - AclCommandOptions: tools/kafka-acls/AclCommandOptions.md
      - AclCommandService: tools/kafka-acls/AclCommandService.md
      - AdminClientService: tools/kafka-acls/AdminClientService.md
      - AuthorizerService: tools/kafka-acls/AuthorizerService.md
    - kafka-console-consumer:
      - ConsoleConsumer: tools/ConsoleConsumer.md
    - kafka-reassign-partitions:
      - tools/kafka-reassign-partitions/index.md
      - Demo: tools/kafka-reassign-partitions/demo.md
      - ReassignPartitionsCommand: tools/kafka-reassign-partitions/ReassignPartitionsCommand.md
    - kafka-replica-verification:
      - tools/kafka-replica-verification/index.md
      - ReplicaBuffer: tools/kafka-replica-verification/ReplicaBuffer.md
      - ReplicaFetcher: tools/kafka-replica-verification/ReplicaFetcher.md
      - ReplicaVerificationTool: tools/kafka-replica-verification/ReplicaVerificationTool.md
  - Metrics:
    - metrics/index.md
    - KafkaMetricsGroup: metrics/KafkaMetricsGroup.md
    - MetricConfig: metrics/MetricConfig.md
    - Metrics: metrics/Metrics.md
    - MetricsReporter: metrics/MetricsReporter.md
    - Sensor: metrics/Sensor.md
  - KRaft:
    - raft/index.md
    - BrokerServer: raft/BrokerServer.md
    - ControllerServer: raft/ControllerServer.md
    - KafkaRaftManager: raft/KafkaRaftManager.md
    - KafkaRaftServer: raft/KafkaRaftServer.md
    - MetaProperties: raft/MetaProperties.md
    - RaftConfig: raft/RaftConfig.md
    - RaftManager: raft/RaftManager.md
  - Misc:
    - Building from Sources: building-from-sources.md
    - Logging: logging.md
    - MetadataCache: MetadataCache.md
    - RequestHandlerHelper: RequestHandlerHelper.md
  - Demos:
    - demo/index.md
    - ACL Authorization: demo/acl-authorization.md
    - Controller Election: demo/controller-election.md
    - Kafka and kcat in Docker: demo/kafka-and-kcat-in-docker.md
    - Secure Inter-Broker Communication: demo/secure-inter-broker-communication.md
    - Securing Communication Between Clients and Brokers Using SSL: demo/securing-communication-between-clients-and-brokers.md
    - SSL Authentication: demo/ssl-authentication.md
    - Transactional Kafka Producer: demo/transactional-kafka-producer.md