site_name: The Internals of Apache Kafka
site_url: https://books.japila.pl/kafka-internals
site_author: Jacek Laskowski
site_description: Demystifying inner-workings of Apache Kafka

repo_name: kafka-internals
repo_url: https://github.com/japila-books/kafka-internals
edit_uri: edit/main/docs/

copyright: Copyright &copy; 2021 Jacek Laskowski

theme:
  name: material
  language: en
  icon:
    logo: material/book-open-page-variant
    repo: fontawesome/brands/github
  features:
    # https://squidfunk.github.io/mkdocs-material/reference/code-blocks/#adding-annotations
    - content.code.annotate
    - navigation.indexes
    - navigation.instant
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: blue
      accent: blue
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

markdown_extensions:
  - admonition
  - codehilite
  - footnotes
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde

plugins:
  - search
  - minify:
      minify_html: true
  - awesome-pages
  - macros
  # https://squidfunk.github.io/mkdocs-material/setup/setting-up-tags/
  # - tags:
  #     tags_file: tags.md

extra:
  analytics:
    provider: google
    property: !ENV GOOGLE_ANALYTICS_KEY
  book:
    title: Apache Kafka
  java:
    api: https://docs.oracle.com/en/java/javase/11/docs/api/java.base
  kafka:
    version: 2.8.0
    github: https://github.com/apache/kafka/tree/2.8.0
  scala:
    api: https://www.scala-lang.org/api/2.12.14
    docs: https://docs.scala-lang.org/
    spec: https://www.scala-lang.org/files/archive/spec/2.12
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/jaceklaskowski
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/jaceklaskowski
    - icon: fontawesome/brands/linkedin
      link: https://linkedin.com/in/jaceklaskowski
    - icon: fontawesome/brands/medium
      link: https://jaceklaskowski.medium.com

nav:
  - Home: index.md
  - Internals:
    - Overview: overview.md
    - AbstractConfig: AbstractConfig.md
    - AutoTopicCreationManager: AutoTopicCreationManager.md
    - BrokerServer: BrokerServer.md
    - Configurable: Configurable.md
    - DefaultAutoTopicCreationManager: DefaultAutoTopicCreationManager.md
    - InterBrokerSendThread: InterBrokerSendThread.md
    - Kafka: Kafka.md
    - KafkaApis: KafkaApis.md
    - KafkaConfig: KafkaConfig.md
    - KafkaServer: KafkaServer.md
    - KafkaRaftServer: KafkaRaftServer.md
    - ReplicaManager: ReplicaManager.md
    - Server: Server.md
    - Utils: Utils.md
  - Transactions:
    - transactions/index.md
    - TransactionConfig: transactions/TransactionConfig.md
    - TransactionCoordinator: transactions/TransactionCoordinator.md
    - TransactionStateManager: transactions/TransactionStateManager.md
  - Clients:
    - clients/index.md
    - Admin:
      - clients/admin/index.md
      - AdminClientRunnable: clients/admin/AdminClientRunnable.md
    - Consumers:
      - clients/consumer/index.md
      - ConsumerNetworkClient: clients/consumer/ConsumerNetworkClient.md
    - Producers:
      - clients/producer/index.md
      - BufferPool: clients/producer/BufferPool.md
      - DefaultPartitioner: clients/producer/DefaultPartitioner.md
      - KafkaProducer: clients/producer/KafkaProducer.md
      - Partitioner: clients/producer/Partitioner.md
      - Producer: clients/producer/Producer.md
      - ProducerBatch: clients/producer/ProducerBatch.md
      - ProducerConfig: clients/producer/ProducerConfig.md
      - RecordAccumulator: clients/producer/RecordAccumulator.md
      - Sender: clients/producer/Sender.md
      - TransactionManager: clients/producer/TransactionManager.md
    - CommonClientConfigs: clients/CommonClientConfigs.md
    - KafkaClient: clients/KafkaClient.md
    - Metadata: clients/Metadata.md
    - MetadataUpdater: clients/MetadataUpdater.md
    - NetworkClient: clients/NetworkClient.md
    - NetworkClientUtils: clients/NetworkClientUtils.md
  - Tools:
    - tools/index.md
    - ReplicaVerificationTool: tools/ReplicaVerificationTool.md
  - Misc:
    - Building from Sources: building-from-sources.md
    - Logging: logging.md
  - Demos:
    - demo/index.md
    - Kafka and kcat in Docker: demo/kafka-and-kcat-in-docker.md
    - Transactional Kafka Producer: demo/transactional-kafka-producer.md